In [2]:
from numpy import *
from slu import *
from splu import *
from splv import *

A função slu usa eliminação Gaussiana para encontrar a decomposição A = LU de uma matriz inversível <b>sem trocar linhas</b>.

In [8]:
A = array([[2,4,-2],[4,9,-3],[-2,-3,7]])
A

array([[ 2,  4, -2],
       [ 4,  9, -3],
       [-2, -3,  7]])

In [4]:
L, U = slu(A)

In [5]:
L

array([[ 1.,  0.,  0.],
       [ 2.,  1.,  0.],
       [-1.,  1.,  1.]])

In [6]:
U

array([[ 2,  4, -2],
       [ 0,  1,  1],
       [ 0,  0,  4]])

In [7]:
L.dot(U)

array([[ 2.,  4., -2.],
       [ 4.,  9., -3.],
       [-2., -3.,  7.]])

Se o algorítmo encontra um pivô igual a zero (ou menor do que um valor pequeno de tolerância), ele para

In [36]:
A = array([[1,1,1],[1,1,3],[2,5,8]])
L,U = slu(A)

Pivô pequeno encontrado na coluna  1


Em uma matriz com entradas aleatórias, os pivôs serão quase sempre diferentes de zero, e slu termina com sucesso.

In [27]:
A = np.random.rand(5, 5)
L, U = slu(A)

In [28]:
A

array([[ 0.39685197,  0.70582262,  0.52393776,  0.30008887,  0.75045268],
       [ 0.42648361,  0.60243446,  0.16089956,  0.25362205,  0.73533587],
       [ 0.95839285,  0.49649295,  0.16504826,  0.57449407,  0.95939056],
       [ 0.86945918,  0.34354483,  0.97678894,  0.40849947,  0.78624105],
       [ 0.90900927,  0.31985077,  0.95703182,  0.11955534,  0.85497441]])

In [29]:
L

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.07466671,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 2.41498823,  7.73953095,  1.        ,  0.        ,  0.        ],
       [ 2.19089039,  7.70605524,  1.45505486,  1.        ,  0.        ],
       [ 2.29054995,  8.30850427,  1.53968965,  2.1253315 ,  1.        ]])

In [30]:
U

array([[ 0.39685197,  0.70582262,  0.52393776,  0.30008887,  0.75045268],
       [ 0.        , -0.15608961, -0.40215891, -0.06887347, -0.07115064],
       [ 0.        ,  0.        ,  2.01226605,  0.38283133, -0.30227126],
       [ 0.        ,  0.        ,  0.        , -0.27526018,  0.1301935 ],
       [ 0.        ,  0.        ,  0.        ,  0.        , -0.08411998]])

Tendo a decomposição LU, é fácil resolver Ax = b. A funcão splv faz isso.

In [35]:
b = arange(10,10 + A.shape[0])
b

array([10, 11, 12, 13, 14])

In [32]:
x = splv(A,b)
x

array([ -75.76804924,  -81.13747738,    6.71527806,   20.18137621,
        116.94644514])

In [33]:
A.dot(x)

array([ 10.,  11.,  12.,  13.,  14.])

Na verdade, splv usa a decomposição PA = LU. Funciona sempre que A for não-singular, desde que não haja erros de arredondamento.

In [38]:
A = array([[1,1,1],[1,1,3],[2,5,8]])
P,L,U,sinal = splu(A)

In [39]:
P

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  1.,  0.]])

In [40]:
L

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  0.],
       [ 2.,  0.,  1.]])

In [41]:
U

array([[1, 1, 1],
       [0, 3, 6],
       [0, 0, 2]])

In [43]:
sinal

-1

sinal é o determinante de P, igual a +1 ou -1 (de acordo com a paridade das trocas linhas)