In [2]:
import numpy as np

In [3]:
A = np.array( [[-1,2,2],[-1,-4,-2],[-3,9,7]] )
#A = np.linalg.inv(A)
print(A)

[[-1  2  2]
 [-1 -4 -2]
 [-3  9  7]]


In [4]:
N = 10

v = np.array([1,0,0])

for i in range(0,N):
    vAntigo = v
    
    v = A.dot(v)    
    
    if vAntigo[0]!= 0:
        autovalor = v[0]/vAntigo[0]
        print(autovalor)
    else:
        print("Divisao por zero no autovalor")
        
    norma = np.sqrt( v.dot(v) ) 
    if norma != 0 :
        v = v/norma
        print(v)
    else:
        print("Divisao por zero no autovetor")
        break

-1.0
[-0.30151134 -0.30151134 -0.90453403]
7.0
[-0.23346307  0.36687054 -0.90050042]
3.57142857143
[-0.33186166  0.22566593 -0.91593817]
3.16
[-0.27880057  0.33526651 -0.89992589]
3.05063291139
[-0.31590132  0.27395592 -0.90838016]
3.01659751037
[-0.29189446  0.31759081 -0.90218274]
3.00550206327
[-0.30796797  0.28992683 -0.90614467]
3.00183066362
[-0.29725666  0.30885869 -0.90346266]
3.00060984906
[-0.30437715  0.29645879 -0.90524402]
3.00020324171
[-0.29961691  0.3048129  -0.90405686]


In [5]:
A = np.array( [[-1,2,2],[-1,-4,-2],[-3,9,7]] )
#A = np.random.rand(3,3)
print("Matriz original")
print(A)

N = 10 #iteracoes

for i in range(0,N):
    Q , R = np.linalg.qr(A)
    A = R.dot(Q)
    print("Iteracão:")
    print(A)

Matriz original
[[-1  2  2]
 [-1 -4 -2]
 [-3  9  7]]
Iteracão:
[[ 7.          4.89897949 -5.90839157]
 [-5.71547607 -4.92592593  2.02124272]
 [ 0.24618298 -0.08933669 -0.07407407]]
Iteracão:
[[ 2.47497219  8.1831979   9.51825695]
 [ 0.431891   -1.27956989  1.65647608]
 [-0.02350187 -0.31128409  0.8045977 ]]
Iteracão:
[[  3.73303965e+00   8.12727301e+00  -9.00222429e+00]
 [ -4.61019778e-01  -2.62126269e+00  -3.04896106e-01]
 [  8.34182946e-03  -7.92301796e-02   8.88223046e-01]]
Iteracão:
[[  2.68534456e+00   8.22717912e+00   9.41883999e+00]
 [  1.94138763e-01  -1.67529681e+00   1.24897660e+00]
 [ -2.19953580e-03  -6.03273407e-02   9.89952252e-01]]
Iteracão:
[[  3.26058614e+00   8.09262557e+00  -9.29689272e+00]
 [ -1.63792009e-01  -2.24428954e+00  -6.43345893e-01]
 [  8.03869224e-04  -2.33403895e-02   9.83703397e-01]]
Iteracão:
[[  2.84715806e+00   8.21987007e+00   9.36781386e+00]
 [  9.18248750e-02  -1.84826995e+00   1.06983202e+00]
 [ -2.46528150e-04  -1.38311811e-02   1.00111189e+00]]

In [6]:
#A = np.array( [[-1,2,2],[-1,-4,-2],[-3,9,7]] )
A = np.random.rand(3,3)
A = A.dot(np.transpose(A))
print("Matriz original (simetrica)")
print(A)

N = 3

S = np.identity(3)
for i in range(0,N):
    Q , R = np.linalg.qr(A)
    A = R.dot(Q)
    S = S.dot(Q)
    print("Iteracão:")
    print(A)
    
print("Autovalores:")
print(A)
print("Autovetores:")
print(S)
print("Matriz original:")
print(S.dot(A).dot(np.transpose(S)))

Matriz original (simetrica)
[[ 1.01117019  0.94627149  0.4415829 ]
 [ 0.94627149  0.9154115   0.33560833]
 [ 0.4415829   0.33560833  0.653301  ]]
Iteracão:
[[ 2.11399866 -0.08375744 -0.01965928]
 [-0.08375744  0.44969686  0.05949207]
 [-0.01965928  0.05949207  0.01618717]]
Iteracão:
[[  2.11824412e+00  -1.83684824e-02   7.62945155e-05]
 [ -1.83684824e-02   4.53497879e-01  -1.06856093e-03]
 [  7.62945155e-05  -1.06856093e-03   8.14069446e-03]]
Iteracão:
[[  2.11843749e+00  -3.93090760e-03  -2.93107453e-07]
 [ -3.93090760e-03   4.53307069e-01   1.91686286e-05]
 [ -2.93107453e-07   1.91686286e-05   8.13813097e-03]]
Autovalores:
[[  2.11843749e+00  -3.93090760e-03  -2.93107453e-07]
 [ -3.93090760e-03   4.53307069e-01   1.91686286e-05]
 [ -2.93107453e-07   1.91686286e-05   8.13813097e-03]]
Autovetores:
[[-0.68562522 -0.16346578 -0.70936379]
 [-0.63811676 -0.3339904   0.69372719]
 [-0.35032136  0.92829378  0.12468199]]
Matriz original:
[[ 1.01117019  0.94627149  0.4415829 ]
 [ 0.94627149  0.